services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_crm_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    env_file:
      - .env
    networks:
      - githubcrm_network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: github_crm_db
    restart: always
    environment:
      POSTGRES_DB: github_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - githubcrm_network

volumes:
  pgdata:

networks:
  githubcrm_network:
    external: true
